# Generated by Django 3.2.15 on 2022-08-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220829_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='locationname',
            new_name='locationName',
        ),
    ]
