# Generated by Django 4.1.1 on 2022-09-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('naver', 'Naver'), ('kakao', 'Kakao')], default='email', max_length=6),
        ),
    ]
