# Generated by Django 3.2.15 on 2022-08-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220829_0143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
