# Generated by Django 3.2.15 on 2022-09-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressname', models.CharField(max_length=100, verbose_name='address_name')),
                ('locationName', models.CharField(max_length=50, verbose_name='location_name')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='lat')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='long')),
            ],
        ),
    ]
