# Generated by Django 3.2.16 on 2022-10-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='locationName',
        ),
    ]
